# Generated by Django 2.1.7 on 2019-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='license',
            field=models.CharField(default='CC-BY-SA-3.0', max_length=64),
        ),
    ]
